export default PIXI.loader
  .add('Default', 'assets/Default.png')
  .add('TestLevel', 'assets/TestLevel.png')
  .add('MenuArrow', 'assets/MenuArrow.png')
  .add('RedCar', 'assets/RedCar.png')
  .add('BlueCar', 'assets/BlueCar.png')
  .add('GreenCar', 'assets/GreenCar.png')
  .add('OrangeCar', 'assets/OrangeCar.png')
  .add('RedStripeCar', 'assets/RedStripeCar.png')
  .add('RektTruck', 'assets/RektTruck.png')
  .add('OrangeTruck', 'assets/OrangeTruck.png')
  .add('wheel', 'assets/wheel.png')
  .add('CarHit', 'assets/CarHit.png')
  .add('TruckHit', 'assets/Truckhit.png')
  .load()
  .resources
